# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/api"
  bin = "tmp/app"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  stop_on_error = true

[log]
  time = true
